# Generated by Django 4.0.6 on 2022-10-03 13:42

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[store.validators.validate_image_size]),
        ),
    ]
